### ISSUE TITLE
Замечания по ДЗ

### ISSUE THREAD

**Issue by ananasn** [litunenko-eg/Itmo_study#1]
* Задание 1 выполнено неверно. "Начиная с 6 символа" не означает, что у символа индекс 6, потому что индексация начинается с 0.  "До 7 символа" в задании не указано, что включая 7ой.  https://github.com/litunenko-eg/Itmo_study/blob/b0f96391482b789cd8d40cad288cb6b7b2178ed7/24.01.2023/main.py#L4
* Задание 3 неверно. Каждый третий символ в строке `"Guido van Rossum is the benevolent dictator for life"` должно вернуть` i nouit nondtof f`

**Comment by litunenko-eg** [comment]
Исправлено
